[package]
name = "deluge-rpc"
version = "0.0.1"
authors = ["The0x539 <the0x539@gmail.com>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Client bindings for the Deluge RPC API."

[dependencies]
serde = { version = "1.0.106", features = ["derive"] }
serde_yaml = "0.8.12"
tokio = { version = "0.2", features = ["full"] }
tokio-rustls = "0.13.0"
rustls = { version = "0.17.0", features = ["dangerous_configuration"] }
libflate = "0.1.27"
base64 = "0.12.1"
deluge-rpc-macro = "0.1.0"
hex = "0.4.2"
rencode = "0.1.0"

[patch.crates-io]
webpki = { path = "./experiment/webpki" }
