[package]
name = "dtui"
version = "0.1.0"
authors = ["The0x539 <the0x539@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.4"
#cursive = "0.14.0"
serde = "1.0.106"
serde_json = "1.0.52"
maplit = "1.0.2"
tokio = { version = "0.2", features = ["full"] }
#webpki-roots = "0.19.0"
tokio-rustls = "0.13.0"
rustls = { version = "0.17.0", features = ["dangerous_configuration"] }

[patch.crates-io]
webpki = { path = "./experiment/webpki" }
