[package]
name = "deluge-rpc"
version = "0.3.1"
authors = ["The0x539 <the0x539@gmail.com>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Client bindings for the Deluge RPC API."
repository = "https://github.com/The0x539/rust-deluge-rpc"

[dependencies]
serde = { version = "1.0.106", features = ["derive"] }
ron = "0.6.0"
tokio = { version = "0.2", features = ["full"] }
tokio-rustls = "0.13.0"
rustls = { version = "0.17.0", features = ["dangerous_configuration"] }
libflate = "0.1.27"
deluge-rpc-macro = "0.4.0"
hex = "0.4.2"
rencode = "0.2.1"
lazy-regex = "0.1.3"
regex = "1.3.7"
lazy_static = "1.4.0"
